### ISSUE TITLE
Outgoing emails in production

### ISSUE THREAD

**Issue by promanapeople** [krayin/krayin-docs#11]
Hi Team

Firstly I have an issue whereby my outgoing emails send fine from dev but on prod (AWS) the send workflow results in a success message but the actual email never arrives, and the (prod) CRM shows the email as being in the Outbox despite confirming it was Sent.

I am using SES, and have another laravel app on the same server which sends email using standard Amazon creds. I have copy pasted those creds into the .env of the CRM: 

```
MAIL_MAILER=smtp
MAIL_HOST=email-smtp.xx.xxxx.xxxxxxxx.xxx
MAIL_PORT=xxxx
MAIL_USERNAME=xxxxxxxxxxxxxxxxxxxxxx
MAIL_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
MAIL_ENCRYPTION=tls
MAIL_DOMAIN=ddddddd.dd
MAIL_FROM_ADDRESS=noreply@ddddddd.dd
MAIL_FROM_NAME="My App Name"
```

The from address is whitelisted on AWS. No error was logged.

Secondly and for my own understanding, I notice this code block in the email controller creates some unique metadata for the email headers. Can you help me understand why the use of `'admin@example.com'` and not `config('mail.from.address')` (for example)?
```
$email = $this->emailRepository->create(array_merge(request()->all(), [
            'source'        => 'web',
            'from'          => 'admin@example.com',
            'user_type'     => 'admin',
            'folders'       => request('is_draft') ? ['draft'] : ['outbox'],
            'name'          => auth()->guard('user')->user()->name,
            'unique_id'     => $uniqueId,
            'message_id'    => $uniqueId,
            'reference_ids' => array_merge($referenceIds, [$uniqueId]),
            'user_id'       => auth()->guard('user')->user()->id,
        ]));

        if (! request('is_draft')) {
            try {
                Mail::send(new Email($email));

                $this->emailRepository->update([
                    'folders' => ['inbox', 'sent']
                ], $email->id);
            } catch (\Exception $e) {}
        }
```

**Comment by devansh-webkul** [comment]
Thank you for reaching out. It looks like your request is not an issue report. For discussions, questions, or general support, we encourage you to use the [Krayin Forum](https://forums.krayincrm.com/). The forum is the best place for such queries, and you'll be able to connect with other community members and get the help you need.

Please reserve the GitHub issue tracker for reporting bugs and issues with the codebase. This helps us keep the issue tracker focused and ensures that problems are addressed promptly.

Thank you for your understanding!
